trip-or-treat/trip-or-treat

.github/workflows/deploy.yml, backend/appspec.yml, backend/scripts/deploy.sh, backend/src/main/java/com/triportreat/backend/HelloController.java
- 테스트용 HelloController 추가.
- deploy.yml, appspec.yml, deploy.sh 파일 추가.
- develop 브랜치로 푸시했을 때 workflow가 실행되도록 변경.
=> CHORE/TOT-2 CI/CD 배포 환경 구성

backend/src/main/resources/application-dev.yml, backend/src/main/resources/application-prod.yml, backend/src/test/resources/application-test.yml
- github actions 스크립트 실행 중 test 시에 에러가 발생해 수정하였습니다.
- "Caused by: org.hibernate.HibernateException at DialectFactoryImpl.java" 해당 로그를 통해 yml DB별 방언(dialect) 인식에 대한 설정 정보를 제거한 것이 문제였음을 파악하였고, 이를 다시 추가해 해결하였습니다.
- 빌드 스크립트 성공, 배포까지 완료됨을 확인하였습니다.
=> TOT-4 : [FIX] CI/CD 빌드 에러 수정

backend/src/main/java/com/triportreat/backend/config/JasyptConfig.java, backend/src/main/java/com/triportreat/backend/place/entity/Place.java, backend/src/main/java/com/triportreat/backend/plan/entity/Plan.java, backend/src/main/java/com/triportreat/backend/region/controller/RegionController.java, backend/src/main/java/com/triportreat/backend/region/entity/Region.java, backend/src/main/java/com/triportreat/backend/region/service/RegionService.java, backend/src/main/java/com/triportreat/backend/region/service/impl/RegionServiceImpl.java, backend/src/main/java/com/triportreat/backend/user/entity/User.java
- JasyptConfig 파일 경로 변경
- place, region, user, plan 패키지 구성
=> TOT-39 : [FEAT] 백엔드 패키지 구성

backend/.gitignore, backend/src/main/resources/application.yml, backend/src/test/resources/application-test.yml, backend/src/test/resources/application.yml
- test 패키지에도 기본 설정파일인 "application.yml"을 추가하고, default active profile을 test로 수정
- 개별로 생성한 local 설정 파일을 추적하지 않도록 .gitignore에 등록
- test 설정파일의 h2 콘솔경로에 "/"가 빠져있어 발생했던 에러 해결
=> TOT-41 : [FIX] 작업환경별 profile 설정 변경

backend/src/main/java/com/triportreat/backend/common/BaseTimeEntity.java, backend/src/main/java/com/triportreat/backend/common/config/JasyptConfig.java, backend/src/main/java/com/triportreat/backend/common/config/JpaConfig.java
- JasyptConfig -> common 패키지로 이동.
- 생성일, 수정일 필드를 갖는 BaseTimeEntity.java 생성
- JpaAuditing 활성화 설정 파일 JpaConfig.java 생성
- 엔티티 클래스가 추상화 클래스인 BaseTimeEntity를 상속하면 자동으로 생성일, 수정일 추적해 값을 저장해줍니다.
- 나중에 단위테스트/통합테스트를 편하게 하기 위해 메인 클래스 BackendApplication.java에 @EnableJpaAuditing 어노테이션을 두지 않고 따로 설정클래스 JpaConfig.java를 생성해 두었습니다.
- DDL 문을 적은 sql 파일에는 생성일, 수정일 까지 포함해 작성하겠습니다. 
- PR 템플릿 정상적으로 불러와집니다.
=> TOT-40 : [FEAT] JpaAuditing 기능 적용

frontend/.eslintrc.json, frontend/.gitignore, frontend/.prettierrc, frontend/README.md, frontend/package-lock.json, frontend/package.json, frontend/public/index.html, frontend/public/manifest.json, frontend/public/robots.txt, frontend/src/App.tsx, frontend/src/index.tsx, frontend/src/routes.tsx, frontend/src/styles/GlobalStyle.tsx, frontend/src/styles/theme.ts, frontend/tsconfig.json
네. 
네
네
초기 세팅 및 라이브러리 설치
1. CRA 
2. Tsconfig
3. esLint
4. prettier 
5. Recoil
6. Styled-components 
7. react-query
8. react-datePicker 
9. Axios 
10. MSW 
문제가 없는지 빠른 확인 부탁드립니다.
tsconfig : https://codingapple.com/unit/typescript-tsconfig-json/ 
prettier & esLint :
-  https://velog.io/@sonic/CRA%EC%97%90-ESLint-%EC%99%80-Prettier-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0 
- https://velog.io/@2wndrhs/%EC%95%8C%EC%95%84%EB%91%90%EB%A9%B4-%EC%93%B8%EB%8D%B0%EC%9E%88%EB%8A%94-ESLint-Prettier-%EC%84%A4%EC%A0%95-%EB%B0%A9%EB%B2%95 
createBrowserRouter: https://noah-dev.tistory.com/38
=> TOT-11 : [CHORE] 프론트엔드 초기 세팅

frontend/.eslintrc.json, frontend/package-lock.json, frontend/package.json, frontend/src/components/RegionModal/RegionModal.tsx, frontend/src/layouts/TestLayout.tsx, frontend/src/pages/TestPage.tsx
네
네
네
1.  styled-components types만 설치해서 발생한 문제 해결
2.  esLint 수정 
2-1. 버전문제로 인한  "plugin:@typescript-eslint/parser" 속성 제거 
2-2. 함수선언식, 화살표함수 둘 다 사용가능하도록 수정 
3. 폴더를 나타내기 위해 임시 파일 추가 
1. 수정사항에 문제가 없는지 확인 부탁드립니다.
- [eslint-parser 문제 해결](https://velog.io/@gyuri092/%EC%97%90%EB%9F%AC-%ED%95%B4%EA%B2%B0-Failed-to-load-config-typescript-eslintparser-to-extend-from)
- [styled-components 문제 해결](https://velog.io/@euji42/Styled-Components%EC%99%80-Typescript-%EC%B4%88%EA%B8%B0-%EC%84%A4%EC%A0%95)
=> TOT-43 : [FIX] 프론트엔드 초기세팅 문제 해결

backend/scripts/deploy.sh
- EC2 인스턴스에서 jar파일 실행 시 develop 프로파일을 사용하도록 수정
=> TOT-47 : [FEAT] jar파일 실행 시 profile을 develop으로 설정

backend/src/main/java/com/triportreat/backend/place/entity/Place.java, backend/src/main/resources/schema.sql
> 1. PR 및 Commit title을 형식에 맞게 작성했나요(e.g. TOT-123 : [TYPE]) O
> 2. Reviewers가 명확하게 지정됐나요? O
> 3. Assignees가 명확하게 지정됐나요? O
- schema.sql에서 불필요한 주석 삭제 및 use dev 구문 삭제
- Place와 ContentType 관계를 일대일에서 다대일로 변경으로 인한 어노테이션 변경
- schema.sql 및 Place 엔티티 클래스의 contentType 필드 확인
=> TOT-49 : [DOCS] schema.sql 수정 및 Place,ContentType 연관관계 수정

frontend/src/components/DayCategory copy/DayCategory.tsx, frontend/src/components/DayCategory copy/index.ts, frontend/src/components/StepNavBar/StepNavBar.tsx, frontend/src/pages/StepThreePage.tsx
> 1. PR 및 Commit title을 형식에 맞게 작성했나요(e.g. TOT-123 : [TYPE])  ✅
> 2. Reviewers가 명확하게 지정됐나요?  ✅
> 3. Assignees가 명확하게 지정됐나요?  ✅
- 날짜 카테고리 기능 구현 
https://github.com/trip-or-treat/trip-or-treat/assets/55423198/21056bba-f43d-4307-ab18-dbffff6226c6
- Day관련 Data 구조에 따라서 기능구현 방법이 달라질 것 같아서 일단 디자인만 봐주시면 될 것 같습니다.
=> TOT-23 : [FEAT] 날짜 카테고리 기능 구현

frontend/.eslintrc.json, frontend/package.json, frontend/public/mockServiceWorker.js, frontend/src/@types/api/contentType.ts, frontend/src/api/contentType.ts, frontend/src/api/index.ts, frontend/src/components/ContentTypeFilterItemList/ContentTypeFilterItemList.tsx, frontend/src/constants/api.ts, frontend/src/hooks/api/useContentType.ts, frontend/src/index.tsx, frontend/src/mocks/browser.ts, frontend/src/mocks/data/contentType.ts, frontend/src/mocks/handlers/contentType.ts, frontend/src/mocks/handlers/index.ts
> 1. PR 및 Commit title을 형식에 맞게 작성했나요(e.g. TOT-123 : [TYPE]) ✅
> 2. Reviewers가 명확하게 지정됐나요? ✅
> 3. Assignees가 명확하게 지정됐나요? ✅
- msw 설정 및 적용
- msw, axios등 약속한 초기설정에 문제없는지 확인바랍니다.
- 폴더 분리가 잘 됐는지 확인바랍니다. 
- [행록](https://github.com/woowacourse-teams/2023-hang-log)
- [줍줍](https://github.com/woowacourse-teams/2022-pickpick)
=> TOT-56 : [CHORE] MSW 설정 및 적용

backend/src/test/java/com/triportreat/backend/region/controller/RegionControllerTest.java
> 1. PR 및 Commit title을 형식에 맞게 작성했나요(e.g. TOT-123 : [TYPE]) O
> 2. Reviewers가 명확하게 지정됐나요? O
> 3. Assignees가 명확하게 지정됐나요? O
- RegionController 응답 내용 검증 테스트 코드 수정
=> TOT-70 : [FIX] RegionController 테스트 코드 수정

backend/src/test/java/com/triportreat/backend/contenttype/repository/ContentTypeRepositoryTest.java, backend/src/test/resources/import.sql
- import.sql 파일 삭제
- 테스트 내에서 직접 데이터를 생성하고 저장하는 방식으로 변경
네
네
네
ContentTypeRepositoryTest의 테스트 데이터 생성 로직 변경
- import.sql 파일 삭제
- 테스트 내에서 직접 데이터를 생성하고 저장하는 방식으로 변경
=> TOT-72 : [FIX] ContentTypeRepository 테스트 데이터 생성 로직 수정

.github/workflows/frontdeploy.yml
pr -> develop push
✅
✅
✅
- action 동작 시기 변경
=> TOT-73 : [CHORE] git action 동작 시기 변경

backend/src/main/java/com/triportreat/backend/common/config/WebConfig.java
=> TOT-75 :  [FIX] CORS 에러 관련 설정 추가

.github/workflows/deploy.yml, backend/src/main/java/com/triportreat/backend/common/config/WebConfig.java
> 1. PR 및 Commit title을 형식에 맞게 작성했나요(e.g. TOT-123 : [TYPE]) o
> 2. Reviewers가 명확하게 지정됐나요? o
> 3. Assignees가 명확하게 지정됐나요? o
- 프론트 로컬 및 배포환경에서 서버 API 호출이 가능하도록 Origin 설정 추가
=> TOT-86 :  [FIX] CORS 에러 핸들링

backend/src/test/java/com/triportreat/backend/contenttype/controller/ContentTypeControllerTest.java
=> TOT-87 : [REFACTOR] 장소 카테고리 목록 조회 요청 URI 수정

backend/src/main/java/com/triportreat/backend/place/service/ExternalApiService.java
=> TOT-89 : [FEAT] 장소 공통정보조회 API 수정

backend/src/main/java/com/triportreat/backend/place/service/impl/ContentTypeServiceImpl.java, backend/src/test/java/com/triportreat/backend/contenttype/service/ContentTypeServiceTest.java
네
네
네
'축제공연행사', '여행코스' 카테고리 필터링 로직 추가
=> TOT-88 : [FEAT] 장소 카테고리 목록 조회 API 필터링 기능 구현

backend/src/main/java/com/triportreat/backend/place/controller/PlaceController.java, backend/src/test/java/com/triportreat/backend/place/controller/PlaceControllerTest.java
=> TOT-90: [FEAT] 장소 공통 정보 조회 API URL 패턴 변경

frontend/package-lock.json, frontend/package.json, frontend/src/api/contentType.ts, frontend/src/api/regions.ts, frontend/src/atoms/contentTypeIdAtom.ts, frontend/src/atoms/curDayAtom.ts, frontend/src/atoms/myRegionListAtom.ts, frontend/src/atoms/placeClickedIdListAtom.ts, frontend/src/atoms/regionClickedIdListAtom.ts, frontend/src/atoms/regionsAtom.ts, frontend/src/atoms/totalPlanAtom.ts, frontend/src/components/ContentTypeFilterItemList/ContentTypeFilterItemList.tsx, frontend/src/components/MyRegionList/MyRegionList.tsx, frontend/src/components/PlaceList/PlaceList.tsx, frontend/src/components/SearchRegionList/SearchRegionList.tsx, frontend/src/components/StepNavBar/StepNavBar.tsx, frontend/src/components/main/RegionList/RegionList.tsx, frontend/src/constants/api.ts, frontend/src/layouts/StepLayout.tsx, frontend/src/pages/StepOnePage.tsx
> 1. PR 및 Commit title을 형식에 맞게 작성했나요(e.g. TOT-123 : [TYPE]) ✅ 
> 2. Reviewers가 명확하게 지정됐나요? ✅ 
> 3. Assignees가 명확하게 지정됐나요? ✅ 
- 실제 api 연동
- recoil-persist 추가
- 같이 진행한 부분이라 따로 요구사항은 없습니다. 
- 
- [recoil-persist](https://www.npmjs.com/package/recoil-persist)
=> TOT-27 : [FEAT] 실제 api 연동

frontend/src/components/common/CommonButton/CommonButton.tsx
> 1. PR 및 Commit title을 형식에 맞게 작성했나요(e.g. TOT-123 : [TYPE]) ✅
> 2. Reviewers가 명확하게 지정됐나요? ✅
> 3. Assignees가 명확하게 지정됐나요? ✅
- 계획저장 페이지 빌드 실패를 해결하기 위해 코드 수정
- CommonButton을 onClick 속성을 추가했는데, 기존에 사용하던 코드는 onClick을 사용하지 않는 부분이 있기 때문에 onClick을 선택적으로 받을 수 있도록 코드를 수정했습니다.
=> TOT-21 : [FIX] CommonButton onClick 옵션 선택적으로 받도록 수정

frontend/src/api/placeList.ts, frontend/src/atoms/contentTypeIdAtom.ts, frontend/src/atoms/myRegionListAtom.ts, frontend/src/components/ContentTypeFilterItemList/ContentTypeFilterItem.tsx, frontend/src/components/EnterSearch/EnterSearch.tsx, frontend/src/components/MyRegionList/MyRegionList.tsx, frontend/src/components/PlaceList/PlaceCard.tsx, frontend/src/components/PlaceList/PlaceList.tsx, frontend/src/components/PlansList/PlansListCard.tsx, frontend/src/components/RegionCategory.tsx, frontend/src/components/SearchRegionList/SearchRegionList.tsx, frontend/src/components/SelectedPlaceCardList/SelectedPlaceCardList.tsx, frontend/src/components/StepNavBar/StepNavLinkButton.tsx, frontend/src/components/common/RegionCard/RegionCard.tsx, frontend/src/constants/color.ts, frontend/src/hooks/api/useInfinityScroll.ts, frontend/src/pages/StepThreePage.tsx, frontend/src/pages/StepTwoPage.tsx
> 1. PR 및 Commit title을 형식에 맞게 작성했나요(e.g. TOT-123 : [TYPE]) ✅
> 2. Reviewers가 명확하게 지정됐나요? ✅
> 3. Assignees가 명확하게 지정됐나요? ✅
- step2, step3 연결시 발생한 문제 해결
https://github.com/trip-or-treat/trip-or-treat/assets/55423198/2de1e5f7-a2c4-4f5a-a610-44b4f067ff75
- 문제없는지 확인 부탁드립니다.
=> TOT-25 : [FEAT] step1,step2 연결

backend/src/main/java/com/triportreat/backend/place/controller/ReviewController.java, backend/src/main/java/com/triportreat/backend/place/domain/ReviewListDto.java, backend/src/main/java/com/triportreat/backend/place/repository/ReviewRepository.java, backend/src/main/java/com/triportreat/backend/place/service/ReviewListService.java, backend/src/main/java/com/triportreat/backend/place/service/impl/ReviewListServiceImpl.java, backend/src/test/java/com/triportreat/backend/place/controller/ReviewControllerTest.java, backend/src/test/java/com/triportreat/backend/place/repository/ReviewRepositoryTest.java, backend/src/test/java/com/triportreat/backend/place/service/impl/ReviewListServiceImplTest.java
> 1. PR 및 Commit title을 형식에 맞게 작성했나요(e.g. TOT-123 : [TYPE])네
> 2. Reviewers가 명확하게 지정됐나요?네
> 3. Assignees가 명확하게 지정됐나요?네
리뷰의 별점이 정수 단위로 측정 되는 것으로 결정됐는데, Review의 score 타입을 Float에서 Integer로 바꿔야 할까요?
=> TOT-77 : [FEAT] 장소 리뷰 조회 API 구현

backend/src/main/java/com/triportreat/backend/place/controller/PlaceController.java, backend/src/main/java/com/triportreat/backend/place/domain/PlaceCommonInfoDto.java, backend/src/main/java/com/triportreat/backend/place/domain/PlaceInfoDto.java, backend/src/main/java/com/triportreat/backend/place/service/PlaceService.java, backend/src/main/java/com/triportreat/backend/place/service/impl/PlaceServiceImpl.java, backend/src/test/java/com/triportreat/backend/place/controller/PlaceControllerTest.java, backend/src/test/java/com/triportreat/backend/place/service/impl/PlaceServiceImplTest.java
> 1. PR 및 Commit title을 형식에 맞게 작성했나요(e.g. TOT-123 : [TYPE])네
> 2. Reviewers가 명확하게 지정됐나요?네
> 3. Assignees가 명확하게 지정됐나요?네
- imageOrigin -> imageThumbnail로 변경
- 응답 데이터에 address 필드 추가
- PlaceCommonInfo -> PlaceInfo 형식으로 메서드 및 클래스 이름 변경
=> TOT-94 : [FEAT] 장소 공통 정보 조회 API 주소 응답 추가

frontend/src/atoms/contentTypeIdAtom.ts, frontend/src/atoms/homeModalAtom.ts, frontend/src/components/RegionCategory.tsx, frontend/src/components/common/Nav/LogoButton.tsx, frontend/src/components/common/Nav/Nav.tsx, frontend/src/hooks/useInitData.ts, frontend/src/layouts/CommonLayout.tsx, frontend/src/layouts/StepLayout.tsx, frontend/src/pages/MainPage.tsx, frontend/src/pages/PlansPage.tsx
> 1. PR 및 Commit title을 형식에 맞게 작성했나요(e.g. TOT-123 : [TYPE]) ✅
> 2. Reviewers가 명확하게 지정됐나요? ✅
> 3. Assignees가 명확하게 지정됐나요? ✅
- 상단 nav바 클릭 시 알람모달을 통해 한번 더 확인절차 추가
- 지역명 이름 제한
- 지역이 바뀌어도 장소가 저장되어있는 문제 수정
=> TOT-97 : [FIX] 1차시 완성 전 발생한 문제들 수정
